version: '3.8'
name: adventureworks2019
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5124:8080"
    depends_on:
      - db
    environment:
      - DefaultConnection=Server=sql,1433;Database=AdventureWorks2019;User=sa;Password=My_StrongPassword62
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      MSSQL_SA_PASSWORD: "My_StrongPassword62"
      ACCEPT_EULA: "Y"
    volumes: 
      - sqlserver-data:/my/file/path
    ports:
      - "1433:1433" 

  nextjs:
    build:
      context: /ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  sqlserver-data: